# Generated by Django 5.1.7 on 2025-03-23 05:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiDaiLy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_dai_ly', models.CharField(max_length=50, verbose_name='Tên Loại Đại Lý')),
                ('no_toi_da', models.DecimalField(decimal_places=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Nợ Tối Đa')),
            ],
            options={
                'verbose_name': 'Loại Đại Lý',
                'verbose_name_plural': 'Loại Đại Lý',
            },
        ),
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quan', models.CharField(max_length=50, verbose_name='Tên Quận')),
            ],
            options={
                'verbose_name': 'Quận',
                'verbose_name_plural': 'Quận',
            },
        ),
        migrations.CreateModel(
            name='QuyDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quy_dinh', models.CharField(max_length=100, unique=True, verbose_name='Tên Quy Định')),
                ('gia_tri', models.CharField(max_length=4000, verbose_name='Giá Trị')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô Tả')),
            ],
            options={
                'verbose_name': 'Quy Định',
                'verbose_name_plural': 'Quy Định',
            },
        ),
        migrations.CreateModel(
            name='DaiLy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dai_ly', models.CharField(max_length=100, verbose_name='Tên Đại Lý')),
                ('dien_thoai', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có 10-11 chữ số.', regex='^\\d{10,11}$')], verbose_name='Điện Thoại')),
                ('dia_chi', models.CharField(max_length=200, verbose_name='Địa Chỉ')),
                ('ngay_tiep_nhan', models.DateField(auto_now_add=True, verbose_name='Ngày Tiếp Nhận')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('tien_no', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tiền Nợ')),
                ('loai_dai_ly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dai_lys', to='api.loaidaily', verbose_name='Loại Đại Lý')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dai_lys', to='api.quan', verbose_name='Quận')),
            ],
            options={
                'verbose_name': 'Đại Lý',
                'verbose_name_plural': 'Đại Lý',
            },
        ),
    ]
